from app.extensions import db
from sqlalchemy.dialects.mysql import LONGTEXT


LONG_TEXT = db.Text().with_variant(LONGTEXT(), "mysql")


class Article(db.Model):
    __tablename__ = "article"
    __table_args__ = (
        db.UniqueConstraint("platform", "source_article_id", name="uq_article_platform_source_id"),
    )

    id = db.Column(db.Integer, primary_key=True)
    event_id = db.Column(db.Integer, db.ForeignKey("event.id"), nullable=True)
    crawl_task_id = db.Column(db.Integer, nullable=True, index=True)
    platform = db.Column(db.String(50), nullable=False)
    source_type = db.Column(db.String(20), nullable=False, default="news")
    source_layer = db.Column(db.String(24), nullable=False, default="unknown", server_default="unknown")
    source_role = db.Column(db.String(32), nullable=False, default="unknown", server_default="unknown")
    source_article_id = db.Column(db.String(255), nullable=True)
    url = db.Column(db.String(2048), nullable=False)
    url_hash = db.Column(db.String(64), unique=True, nullable=False, index=True)
    title = db.Column(db.String(500), nullable=False)
    raw_content = db.Column(LONG_TEXT)
    clean_content = db.Column(LONG_TEXT)
    raw_json = db.Column(db.JSON)
    content_type = db.Column(db.String(20))
    language = db.Column(db.String(20), default="unknown")
    clean_status = db.Column(db.String(20), default="pending")
    clean_error = db.Column(db.Text)
    extraction_method = db.Column(db.String(32))
    extraction_degraded = db.Column(db.Boolean, default=False)
    processing_warnings = db.Column(db.JSON)
    normalize_version = db.Column(db.String(20))
    preprocess_version = db.Column(db.String(20))
    quality_score = db.Column(db.Float)
    quality_level = db.Column(db.String(20))
    quality_flags = db.Column(db.JSON)
    nlp_weight = db.Column(db.Float, default=1.0)
    is_advertisement = db.Column(db.Boolean, default=False)
    advertisement_score = db.Column(db.Float)
    advertisement_reasons = db.Column(db.JSON)
    is_duplicate = db.Column(db.Boolean, default=False)
    duplicate_of_id = db.Column(db.Integer, db.ForeignKey("article.id"), nullable=True)
    duplicate_group_id = db.Column(db.String(64))
    duplicate_method = db.Column(db.String(30))
    duplicate_score = db.Column(db.Float)
    content_hash = db.Column(db.String(64))
    simhash = db.Column(db.String(16))
    dedup_version = db.Column(db.String(20))
    author = db.Column(db.String(100))
    author_id = db.Column(db.String(255))
    author_followers = db.Column(db.BigInteger, nullable=True)
    author_verified = db.Column(db.Boolean, nullable=True)
    author_type = db.Column(db.String(50))
    publish_time = db.Column(db.DateTime, nullable=True)
    comments_count = db.Column(db.BigInteger, nullable=True)
    reposts_count = db.Column(db.BigInteger, nullable=True)
    likes_count = db.Column(db.BigInteger, nullable=True)
    views_count = db.Column(db.BigInteger, nullable=True)
    engagement_score = db.Column(db.Float)
    duplicate_weight = db.Column(db.Float, default=1.0)
    spam_weight = db.Column(db.Float, default=1.0)
    heat_contribution = db.Column(db.Float)
    source_reliability_score = db.Column(db.Float)
    sentiment_label = db.Column(db.String(10))
    sentiment_score = db.Column(db.Float)
    sentiment_reason = db.Column(db.Text)
    sentiment_method = db.Column(db.String(20))
    sentiment_confidence = db.Column(db.Float)
    sentiment_dimension = db.Column(db.String(16))
    sentiment_target = db.Column(db.String(200))
    sentiment_content_identity = db.Column(db.String(80))
    current_sentiment_result_id = db.Column(db.BigInteger, nullable=True, index=True)
    sentiment_analyzed_at = db.Column(db.DateTime)
    is_suspicious = db.Column(db.Boolean, default=False)
    suspicious_score = db.Column(db.Float)
    suspicious_reason = db.Column(db.Text)
    suspicious_method = db.Column(db.String(20))
    first_crawled_at = db.Column(db.DateTime, server_default=db.func.now())
    last_crawled_at = db.Column(db.DateTime, server_default=db.func.now(), onupdate=db.func.now())
    content_version = db.Column(db.Integer, default=1)
    latest_snapshot_id = db.Column(db.BigInteger, nullable=True)
