-- Event aggregation runs, evidence, stable membership and versioned representations.

CREATE TABLE IF NOT EXISTS aggregation_run (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    analysis_run_id BIGINT NOT NULL,
    hotspot_run_id BIGINT NULL,
    source_task_id BIGINT NULL,
    user_id INT NULL,
    scope VARCHAR(24) NOT NULL,
    mode VARCHAR(20) NOT NULL,
    attempt INT NOT NULL DEFAULT 1,
    query_fingerprint CHAR(64) NULL,
    dataset_hash CHAR(64) NOT NULL,
    config_hash CHAR(64) NOT NULL,
    config JSON NULL,
    versions JSON NULL,
    statistics JSON NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    warnings JSON NULL,
    error_code VARCHAR(64) NULL,
    error_message TEXT NULL,
    cache_expires_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at DATETIME NULL,
    completed_at DATETIME NULL,
    UNIQUE KEY uq_aggregation_run_fingerprint (analysis_run_id, hotspot_run_id, scope, mode, config_hash, attempt),
    INDEX ix_aggregation_run_status_created (status, created_at),
    INDEX ix_aggregation_run_query_cache (query_fingerprint, cache_expires_at),
    CONSTRAINT fk_aggregation_run_analysis FOREIGN KEY (analysis_run_id) REFERENCES analysis_run(id),
    CONSTRAINT fk_aggregation_run_hotspot FOREIGN KEY (hotspot_run_id) REFERENCES hotspot_run(id),
    CONSTRAINT fk_aggregation_run_task FOREIGN KEY (source_task_id) REFERENCES task(id),
    CONSTRAINT fk_aggregation_run_user FOREIGN KEY (user_id) REFERENCES user(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS aggregation_cluster (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    aggregation_run_id BIGINT NOT NULL,
    cluster_index INT NOT NULL,
    resolved_event_id INT NULL,
    title VARCHAR(500) NOT NULL,
    topic_category VARCHAR(30) NULL,
    topic_name VARCHAR(100) NULL,
    keywords JSON NULL,
    entities JSON NULL,
    first_publish_time DATETIME NULL,
    last_activity_time DATETIME NULL,
    representative_article_id INT NULL,
    member_count INT NOT NULL DEFAULT 0,
    platform_count INT NOT NULL DEFAULT 0,
    confidence FLOAT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_aggregation_cluster_run_index (aggregation_run_id, cluster_index),
    INDEX ix_aggregation_cluster_event (resolved_event_id),
    CONSTRAINT fk_aggregation_cluster_run FOREIGN KEY (aggregation_run_id) REFERENCES aggregation_run(id) ON DELETE CASCADE,
    CONSTRAINT fk_aggregation_cluster_event FOREIGN KEY (resolved_event_id) REFERENCES event(id),
    CONSTRAINT fk_aggregation_cluster_article FOREIGN KEY (representative_article_id) REFERENCES article(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS aggregation_assignment (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    aggregation_run_id BIGINT NOT NULL,
    aggregation_cluster_id BIGINT NULL,
    article_id INT NOT NULL,
    content_identity VARCHAR(80) NOT NULL,
    resolved_event_id INT NULL,
    membership_action VARCHAR(24) NOT NULL,
    candidate_event_id INT NULL,
    similarity FLOAT NOT NULL DEFAULT 0,
    score_details JSON NULL,
    decision_reason JSON NULL,
    is_representative BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_aggregation_assignment_run_article (aggregation_run_id, article_id),
    INDEX ix_aggregation_assignment_event (resolved_event_id),
    CONSTRAINT fk_aggregation_assignment_run FOREIGN KEY (aggregation_run_id) REFERENCES aggregation_run(id) ON DELETE CASCADE,
    CONSTRAINT fk_aggregation_assignment_cluster FOREIGN KEY (aggregation_cluster_id) REFERENCES aggregation_cluster(id) ON DELETE CASCADE,
    CONSTRAINT fk_aggregation_assignment_article FOREIGN KEY (article_id) REFERENCES article(id),
    CONSTRAINT fk_aggregation_assignment_event FOREIGN KEY (resolved_event_id) REFERENCES event(id),
    CONSTRAINT fk_aggregation_assignment_candidate FOREIGN KEY (candidate_event_id) REFERENCES event(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS event_article_membership (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    event_id INT NOT NULL,
    article_id INT NOT NULL,
    active_article_id INT NULL,
    source_aggregation_run_id BIGINT NOT NULL,
    confidence FLOAT NOT NULL DEFAULT 0,
    decision_method VARCHAR(64) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    valid_from DATETIME NOT NULL,
    valid_to DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_event_membership_active_article (active_article_id),
    INDEX ix_event_membership_event_active (event_id, is_active),
    INDEX ix_event_membership_article (article_id),
    CONSTRAINT fk_event_membership_event FOREIGN KEY (event_id) REFERENCES event(id),
    CONSTRAINT fk_event_membership_article FOREIGN KEY (article_id) REFERENCES article(id),
    CONSTRAINT fk_event_membership_run FOREIGN KEY (source_aggregation_run_id) REFERENCES aggregation_run(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS event_representation (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    event_id INT NOT NULL,
    model_name VARCHAR(255) NOT NULL,
    model_version VARCHAR(64) NOT NULL,
    preprocess_version VARCHAR(64) NOT NULL,
    dimension INT NOT NULL,
    vector JSON NOT NULL,
    keywords JSON NULL,
    entities JSON NULL,
    member_count INT NOT NULL DEFAULT 0,
    source_aggregation_run_id BIGINT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_event_representation_version (event_id, model_name, model_version, preprocess_version),
    INDEX ix_event_representation_model (model_name, model_version),
    CONSTRAINT fk_event_representation_event FOREIGN KEY (event_id) REFERENCES event(id),
    CONSTRAINT fk_event_representation_run FOREIGN KEY (source_aggregation_run_id) REFERENCES aggregation_run(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS event_merge_record (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    source_event_id INT NOT NULL,
    target_event_id INT NOT NULL,
    aggregation_run_id BIGINT NULL,
    similarity_evidence JSON NULL,
    reason VARCHAR(255) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    reviewed_by INT NULL,
    reviewed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_event_merge_pair_status (source_event_id, target_event_id, status),
    INDEX ix_event_merge_status_created (status, created_at),
    CONSTRAINT fk_event_merge_source FOREIGN KEY (source_event_id) REFERENCES event(id),
    CONSTRAINT fk_event_merge_target FOREIGN KEY (target_event_id) REFERENCES event(id),
    CONSTRAINT fk_event_merge_run FOREIGN KEY (aggregation_run_id) REFERENCES aggregation_run(id),
    CONSTRAINT fk_event_merge_user FOREIGN KEY (reviewed_by) REFERENCES user(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
